AppBundle\Entity\Chain:
    type: entity
    repositoryClass: AppBundle\Services\ChainService
    uniqueConstraints:
    id:
        id:
            type: guid
            generator: { strategy: UUID }
    fields:
        url:
            type: string
