AppBundle\Entity\Chain:
    type: entity
    repositoryClass: AppBundle\Services\ChainService
    uniqueConstraints:
        unique_url:
            columns: [ url ]
    id:
        id:
            type: guid
            generator: { strategy: UUID }
    fields:
        url:
            type: string
        chainId:
            type: string
        createdAt:
            type: datetime
        nodes:
            type: simple_array